### ISSUE TITLE
Session.send() doesn't work as documented.

### ISSUE THREAD

**Issue by Pokute** [ninchat/ninchat-js#4]
https://github.com/ninchat/ninchat-js/blob/815893b59f749c1ada5b8302f2994f923c29c333/docs/ninchatclient.md#sessionsendheader-payload

>If an action_id is used, a Promise is returned. It may be used to wait for a reply from the server; the promise will be resolved with an event header and a payload array parameter. If the Session object is closed before a reply is received, the promise will be rejected without a parameter.

https://github.com/ninchat/ninchat-js/blob/815893b59f749c1ada5b8302f2994f923c29c333/src/ninchatclient/lib/session.go#L146

On the other hand, the code specifically does not create and return a promise if an ```action_id``` is defined.

    if _, disabled := params["action_id"]; !disabled {
       p := &Promise{
       ...

I verified this by removing the !-operator in front of ```!disabled``` in javascript code. This made the API works as expected.

**Comment by tsavola** [comment]
The documentation might be a bit unclear. Important details are in the previous paragraph:

> To send an action without an action_id parameter, specify it as null. Otherwise an action_id is generated automatically.

The caller is not supposed to specify an action_id number. The only valid value for it is null, which disables action_id. By default it is generated implicitly.

The code you quoted should perhaps also check that the value is indeed null, and report an error otherwise. And the documentation should be clarified.
